default_language_version:
  python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.0"]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
    -   id: ruff
        args: ["--force-exclude", "--fix"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
        args: [--config=setup.cfg]
        additional_dependencies: [types-python-dateutil==2.8.16, types-requests]
-   repo: https://github.com/crate-ci/typos
    rev: v1.13.18
    hooks:
      - id: typos
