default_language_version:
  python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.0"]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        -    flake8-bugbear
        -    flake8-no-pep420
        -    flake8-comprehensions
        -    flake8-tidy-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        args: [--config=setup.cfg]
        additional_dependencies: [types-python-dateutil==2.8.16, types-requests]
