version: '3.9'

services:

  django:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/application
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}

  redis:
    image: redis:7.0.8-bullseye
    restart: always
    volumes:
      - redis_data:/data

  celery_worker_respond_to_updates:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A config worker -l info -Q respond_to_updates_queue --concurrency=1"
    volumes:
      - .:/application
    env_file:
      - ./.env
    restart: always
    depends_on:
      - django
      - postgres
      - redis
      - celery_beat

  celery_worker_scrapers:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A config worker -l info -Q scrapers_queue --concurrency=1"
    volumes:
      - .:/application
    env_file:
      - ./.env
    restart: always
    depends_on:
      - django
      - postgres
      - redis
      - celery_beat

  celery_worker_send_messages:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A config worker -l info -Q send_messages_queue --concurrency=1"
    volumes:
      - .:/application
    env_file:
      - ./.env
    restart: always
    depends_on:
      - django
      - postgres
      - redis
      - celery_beat

  celery_beat:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A config beat -l info"
    volumes:
      - .:/application
    env_file:
      - ./.env
    restart: always
    depends_on:
      - django
      - postgres
      - redis

  flower:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A config flower"
    volumes:
      - .:/application
    env_file:
      - ./.env
    ports:
      - 5555:5555
    depends_on:
      - django
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
